// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         return linux;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAQwbU05l6BIkOCapYyseewjNxckIcTsuw',
//     appId: '1:189285904403:web:03a97c21acefa8b3f14fe6',
//     messagingSenderId: '189285904403',
//     projectId: 'cridet-hour-system',
//     authDomain: 'cridet-hour-system.firebaseapp.com',
//     storageBucket: 'cridet-hour-system.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBDEwXMqIrKeZ8Dh2_Y0gYgXRz3mwHtTq8',
//     appId: '1:189285904403:android:6c5d97c49e7e49f1f14fe6',
//     messagingSenderId: '189285904403',
//     projectId: 'cridet-hour-system',
//     storageBucket: 'cridet-hour-system.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDxnix-9hJw0utfDtfxUDqNCODny87gq4g',
//     appId: '1:189285904403:ios:ed6e07fd8a7ba610f14fe6',
//     messagingSenderId: '189285904403',
//     projectId: 'cridet-hour-system',
//     storageBucket: 'cridet-hour-system.appspot.com',
//     iosBundleId: 'com.example.cridetHourSystem',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDxnix-9hJw0utfDtfxUDqNCODny87gq4g',
//     appId: '1:189285904403:ios:605525b99a08fb95f14fe6',
//     messagingSenderId: '189285904403',
//     projectId: 'cridet-hour-system',
//     storageBucket: 'cridet-hour-system.appspot.com',
//     iosBundleId: 'com.example.cridetHourSystem.RunnerTests',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAQwbU05l6BIkOCapYyseewjNxckIcTsuw',
//     appId: '1:189285904403:web:344af703367dcc2df14fe6',
//     messagingSenderId: '189285904403',
//     projectId: 'cridet-hour-system',
//     authDomain: 'cridet-hour-system.firebaseapp.com',
//     storageBucket: 'cridet-hour-system.appspot.com',
//   );
//
//   static const FirebaseOptions linux = FirebaseOptions(
//     apiKey: 'AIzaSyAQwbU05l6BIkOCapYyseewjNxckIcTsuw',
//     appId: '1:189285904403:web:03a97c21acefa8b3f14fe6',
//     messagingSenderId: '189285904403',
//     projectId: 'cridet-hour-system',
//     authDomain: 'cridet-hour-system.firebaseapp.com',
//     storageBucket: 'cridet-hour-system.appspot.com',
//   );
// }



///secret = /WCDZqaqkHuNms1jvmWvO5MGv6YY18opi7ODY0s6
///access key = AKIAU6GDW56YSQPSP6DN