import '../subject_model/subject_model.dart';

class Student_Model {
  String? name;
  String? image;
  double? gpa;
  String? id; // You can use either int or String, depending on your use case
  String? password;
  String? levelar;
  String? phone;
  String? email;
  bool? military;
  bool? isApproved;
  bool? isPaid;
  bool? logOut;
  String? level;
  Map<String, dynamic>? absence;
  List<String>? warning;
  List<String>? bookList;
  List<Subject_Model>? subjects;
  String? studentAddress;
  String? gender;
  String? birthDayImage;
  String? idPhoto;
  String? nomation_c;
  String? nomination_Card;
  String? doneIn;
  String? studentPhone;
  String? father_Phone;
  String? fatherName;
  String? fatherJob;
  String? recruitmentArea;
  String? tripleNumber;
  String? placeBirth;
  String? dateOfBirth;
  String? note;
  String? orderStatus;
  String? transferStatus;
  String? transferType;
  String? approvalDate;
  String? partyTransferred;
  String? cardIssuingParty;
  String? idCardNumber;
  String? degreeTotal;
  String? sittingNumber;
  String? schoolName;
  String? receivedData;
  String? Academic_division;
  String? educationalQualification;
  String? division;
  bool? enroll_Status;
  String? major;
  String? year_now;
  String? soldiers_image_1;
  String? soldiers_image_2;

  // Constructor
  Student_Model({
    required this.name,
    required this.image,
    required this.gpa,
    required this.id,
    required this.password,
    required this.isApproved,
    required this.phone,
    required this.email,
    required this.levelar,
    required this.military,
    required this.level,
    required this.absence,
    required this.warning,
    required this.bookList,
    required this.studentAddress,
    required this.gender,
    required this.birthDayImage,
    required this.idPhoto,
    required this.nomation_c,
    required this.nomination_Card,
    required this.logOut,
    required this.doneIn,
    required this.studentPhone,
    required this.father_Phone,
    required this.fatherName,
    required this.fatherJob,
    required this.soldiers_image_1,
    required this.soldiers_image_2,
    required this.recruitmentArea,
    required this.tripleNumber,
    required this.placeBirth,
    required this.dateOfBirth,
    required this.note,
    required this.orderStatus,
    required this.transferStatus,
    required this.transferType,
    required this.approvalDate,
    required this.subjects,
    required this.partyTransferred,
    required this.cardIssuingParty,
    required this.idCardNumber,
    required this.degreeTotal,
    required this.sittingNumber,
    required this.isPaid,
    required this.schoolName,
    required this.receivedData,
    required this.Academic_division,
    required this.educationalQualification,
    required this.division,
    required this.enroll_Status,
    required this.major,
    required this.year_now,
  });

  // Factory method to create a Student object from a JSON map
  factory Student_Model.fromJson(Map<String, dynamic> json) {
    return Student_Model(
      name: json['Name'],
      logOut: json['logOut'],
      isApproved: json['isApproved'],
      isPaid: json['isPaid'],
      levelar: json['levelar'],
      image: json['Image'],
      soldiers_image_1: json['soldiers_image_1'],
      soldiers_image_2: json['soldiers_image_2'],
      gpa: json['GPA'],
      id: json['ID'],
      password: json['Password'],
      phone: json['Phone'],
      email: json['Email'],
      military: json['Military'],
      level: json['Level'],
      absence: json['Absence'],
      warning: List<String>.from(json['Warning']),
      subjects: (json['subjects'] as List<dynamic>?)
          ?.map((subjectJson) => Subject_Model.fromJson(subjectJson))
          .toList(),
      bookList: List<String>.from(json['Book_List']),
      studentAddress: json['Student_Address'],
      gender: json['Gender'],
      birthDayImage: json['Birth_day_Image'],
      idPhoto: json['ID_photo'],
      nomation_c: json['personal_photo'],
      nomination_Card: json['Nomination_card'],
      doneIn: json['Done_in'],
      studentPhone: json['Student_phone'],
      father_Phone: json['father_Phone'],
      fatherName: json['Fahther_name'],
      fatherJob: json['Father_job'],
      recruitmentArea: json['Recruitment_area'],
      tripleNumber: json['Triple_number'],
      placeBirth: json['Place_birth'],
      dateOfBirth: json['Date_of_birth'],
      note: json['note'],
      orderStatus: json['Order_status'],
      transferStatus: json['Transfer_status'],
      transferType: json['Transfer_type'],
      approvalDate: json['Approval_date'],
      partyTransferred: json['Party_Transferred'],
      cardIssuingParty: json['Thecard_Issuing_Party'],
      idCardNumber: json['ID_card_number'],
      degreeTotal: json['Degre_total'],
      sittingNumber: json['Sitting_Number'],
      schoolName: json['School_Name'],
      receivedData: json['Received_Data'],
      Academic_division: json['Academic_division'],
      educationalQualification: json['Educational_Qualification'],
      division: json['division'],
      enroll_Status: json['enroll_Status'],
      major: json['major'],
      year_now: json['year_now'],
    );
  }

  // Method to convert a Student object to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'Name': name,
      'Image': image,
      'GPA': gpa,
      'subjects': subjects,
      'ID': id,
      'isApproved': isApproved,
      'Password': password,
      'Phone': phone,
      'Email': email,
      'Military': military,
      'Level': level,
      'Absence': absence,
      'Warning': warning,
      'logOut': logOut,
      'Book_List': bookList,
      'Student_Address': studentAddress,
      'Gender': gender,
      'Birth_day_Image': birthDayImage,
      'levelar': levelar,
      'ID_photo': idPhoto,
      'personal_photo': nomation_c,
      'Nomination_card': nomination_Card,
      'soldiers_image_1': soldiers_image_1,
      'soldiers_image_2': soldiers_image_2,
      'Done_in': doneIn,
      'Student_phone': studentPhone,
      'father_Phone': father_Phone,
      'Fahther_name': fatherName,
      'Father_job': fatherJob,
      'Recruitment_area': recruitmentArea,
      'Triple_number': tripleNumber,
      'Place_birth': placeBirth,
      'Date_of_birth': dateOfBirth,
      'note': note,
      'Order_status': orderStatus,
      'Transfer_status': transferStatus,
      'Transfer_type': transferType,
      'Approval_date': approvalDate,
      'Party_Transferred': partyTransferred,
      'Thecard_Issuing_Party': cardIssuingParty,
      'ID_card_number': idCardNumber,
      'Degre_total': degreeTotal,
      'Sitting_Number': sittingNumber,
      'School_Name': schoolName,
      'Received_Data': receivedData,
      'Academic_division': Academic_division,
      'Educational_Qualification': educationalQualification,
      'division': division,
      'enroll_Status': enroll_Status,
      'major': major,
      'year_now': year_now,
      'isPaid': isPaid,
    };
  }
}

